### ISSUE TITLE
[Tracking] Website of card thumbnails

### ISSUE THREAD

**Issue by jishanshaikh4** [jishanshaikh4/latex-templates#10]
- [ ] Add index.html
- [ ] index all the cards according to design and popularity
- [ ] link it to the /latex-templates
